root: true
env:
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'htmlacademy/node'
  - 'prettier'
# node/no-unsupported-features/es-syntax:
#   - error
#   - version: '>=8.0.0'
#     ignores:
#       - dynamicImport
