# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
   "username": "Morgan",
   "email": "morgan1@gmail.com",
   "password": "morgan",
   "isPro": true
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
   "email": "morgan@gmail.com",
   "password": "morgan"
}

###

## Отправить изображение

POST http://localhost:5000/users/6546073972e37b7f13719fa3/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=avatar; filename='section-decor.png'
Content-Type: image/png

< \web-projects\candles\images\section-decor.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя

GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbkBnbWFpbC5jb20iLCJpZCI6IjY1M2E2NTY0OWU0MjYzMDg4ZDBjZjFkZSIsImlhdCI6MTY5ODQwODUxMywiZXhwIjoxNjk4NTgxMzEzfQ.atuKZJvWO9sXRWh4-KHEzLHRQMLNS5UaeGyfHbqhlXU

###
