# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
   "username": "Morgan",
   "email": "morgan@gmail.com",
   "avatar": "avatar-1.jpg",
   "password": "morgan",
   "isPro": true
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
   "email": "morgan@gmail.com",
   "password": "morgan"
}
