# Предложения
## Получить список предложений пользователь не авторизован
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###
## Получить список предложений пользователь авторизован
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbkBnbWFpbC5jb20iLCJpZCI6IjY1M2E2NTY0OWU0MjYzMDg4ZDBjZjFkZSIsImlhdCI6MTY5ODU4NTE2OSwiZXhwIjoxNjk4NzU3OTY5fQ.Fuqi7__JGbIpF2dxo8cdl0khvQTEb5hhJ3frmW05d2I

###
## Получить предложение по идентификатору пользователь не авторизован

GET  http://localhost:5000/offers/65333e0e9df1da5dca706699 HTTP/1.1

###
## Получить предложение по идентификатору пользователь авторизован

GET  http://localhost:5000/offers/65333e0e9df1da5dca706699 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbkBnbWFpbC5jb20iLCJpZCI6IjY1M2E2NTY0OWU0MjYzMDg4ZDBjZjFkZSIsImlhdCI6MTY5ODU4NTE2OSwiZXhwIjoxNjk4NzU3OTY5fQ.Fuqi7__JGbIpF2dxo8cdl0khvQTEb5hhJ3frmW05d2I

###
## Создать новое предложение

POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbjFAZ21haWwuY29tIiwiaWQiOiI2NTRiOTdlNzQyNmUyY2M3YmYzMzI1NzgiLCJpYXQiOjE2OTk0NTI5ODIsImV4cCI6MTY5OTYyNTc4Mn0.TZlH_xYbYv9ZL8WEHph41JWp9-cuJ-7oVOF2ifFLvmI

{
  "title": "Nice, cozy, warm big bed apartment",
  "description": "I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!",
  "date": "2023-10-06T00:45:27.928Z",
  "city": {
    "name": "Hamburg",
    "location": {
      "latitude": 53.550341,
      "longitude": 10.000654
    }
  },
  "imagePreview": "image-7.jpg",
  "images": [
    "image-3.jpg",
    "image-5.jpg",
    "image-13.jpg",
    "image-14.jpg",
    "image-12.jpg",
    "image-6.jpg"
  ],
  "isPremium": true,
  "isFavorite": false,
  "type": "apartment",
  "bedrooms": 5,
  "maxAdults": 10,
  "price": 73639,
  "goods": [
    "Laptop friendly workspace",
    "Baby seat",
    "Washer",
    "Towels"
  ],
  "hostId": "652c13d06ca32aa32aab1714",
  "location": {
    "latitude": 50.916361,
    "longitude": 6.944974
  }
}

###
## Удалить выбранное предложение по идентификатору

DELETE http://localhost:5000/offers/6546078a72e37b7f13719fa6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbkBnbWFpbC5jb20iLCJpZCI6IjY1NDYwNzM5NzJlMzdiN2YxMzcxOWZhMyIsImlhdCI6MTY5OTEwMjYzMiwiZXhwIjoxNjk5Mjc1NDMyfQ.uM1PsEbgER1c8yhTOOp4pmsp0gb1wHCVQsOJJznZbZ8

###
## Обновить выбранное предложение

PATCH  http://localhost:5000/offers/6546078a72e37b7f13719fa6 HTTP/11.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbjFAZ21haWwuY29tIiwiaWQiOiI2NTQ2MzM1OTljYTU1MzJkZDFiYjA5M2QiLCJpYXQiOjE2OTkxMDIzMTIsImV4cCI6MTY5OTI3NTExMn0.PLLUy3hIQMom0S5doyYU0z8j9ePkwgGPqZDSAozlSpo

{
  "price": 5000
}

###
## Получить отзывы для предложения

GET http://localhost:5000/offers/65333e0e9df1da5dca706699/reviews HTTP/1.1

###
## Получить премиальные предложения для города пользователь не авторизован

GET http://localhost:5000/offers/Hamburg/premium HTTP/1.1

###
## Получить премиальные предложения для города пользователь авторизован

GET http://localhost:5000/offers/Hamburg/premium HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbkBnbWFpbC5jb20iLCJpZCI6IjY1M2E2NTY0OWU0MjYzMDg4ZDBjZjFkZSIsImlhdCI6MTY5ODU4NTE2OSwiZXhwIjoxNjk4NzU3OTY5fQ.Fuqi7__JGbIpF2dxo8cdl0khvQTEb5hhJ3frmW05d2I

###

## Загрузить изображение для объявления
POST http://localhost:5000/offers/6546078a72e37b7f13719fa6/imagePreview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1vcmdhbkBnbWFpbC5jb20iLCJpZCI6IjY1NDYwNzM5NzJlMzdiN2YxMzcxOWZhMyIsImlhdCI6MTY5OTA4ODM2OSwiZXhwIjoxNjk5MjYxMTY5fQ.Y6l9CxdPrhnPSKrAtW2nXikXERqkfub0cGXfpYYRlrA
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="screen.png"
Content-Type: image/png

< \web-projects\candles\images\section-decor.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
